# Pandas. Домашнее задание

В домашнем задании есть обязательные и дополнительные задачи.

*Обязательные задачи* нужно сделать, чтобы проверить, что вы действительно усвоили материал модуля. Они обязательны к загрузке на проверку преподавателю.

*Дополнительные задачи* для тех, кто чувствует, что нужно ещё немного потренироваться и порешать задачки по работе с Pandas. Вы также можете загрузить их на проверку преподавателю и получить по ним обратную связь.

Удачи!



---



---



**Цели домашнего задания:**
1. Научиться работать с описательными статистиками набора данных.
2. Научиться выбирать данные по условиям.
3. Научиться объединять несколько датафреймов в один.


**Что входит в домашнее задание:**
1. *Обязательные задачи*:

17 задач с использованием:
- набора рекламных данных, показывающих, щелкнул ли конкретный пользователь интернета рекламу на веб-сайте компании или нет,
- дополнительного набора данных, описывающего пользователей, посещающих веб-сайт компании.
2. *Дополнительные задачи*:

3 задачи для отработки исследования данных.


**Критерии оценки:**
- программа выдаёт верный ответ на заданном наборе данных;
- код читабелен: переменным даны осмысленные названия, отступы и правила расстановки пробелов соблюдены.

**Как отправить задание на проверку**

Выполните задачи, сохраните изменения при помощи опции Save and Checkpoint из вкладки меню File или кнопки Save and Checkpoint на панели инструментов. Отправьте через форму на платформе итоговый файл Jupyter Notebook (в формате .ipynb) или ссылку на него.



---


---



**Обязательные задачи**

В течение всего домашнего задания вы будете работать с несколькими наборами данных:
1. Набор рекламных данных, показывающих, щёлкнул ли конкретный пользователь рекламу на сайте компании или нет. Состоит из трёх разных файлов: `advertising_1.csv`, `advertising_2.csv`, `advertising_3.csv`.

Описание столбцов датасета:
- **Number**: Номер пользователя в системе.
- **Daily Time Spent on Site**: Среднее ежедневное время нахождения пользователя на сайте в минутах.
- **Daily Internet Usage**: Среднее ежедневное время нахождения пользователя в интернете в минутах.
- **Ad Topic Line**: Заголовок рекламного объявления.
- **Clicked on Ad**: Кликнул пользователь на рекламу или нет.

Дополнительный к рекламным данным датасет, который описывает пользователей, посещающих сайт компании. Состоит из одного файла: users.csv.

Описание столбцов датасета:
- **Number**: Номер пользователя в системе.
- **Age**: Возраст пользователя.
- **Male**: Является ли пользователь мужчиной.
- **City**: Город пользователя.
- **Country**: Страна пользователя.
- **Area Income**: Средний доход в месте жительства пользователя.


***Задача 1***

Загрузите таблицу из файла `advertising_1.csv` и сохраните её в датафрейм `adv1_df`. Укажите в качестве индекса столбец `Number`. Выведите на экран первые десять строк.


In [1]:
!pip install pandas

In [2]:
import pandas as pd

In [3]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols=None, squeeze: 'bool | None' = None, prefix: 'str | lib.NoDefault' = <no_default>, mangle_dupe_cols: 'bool' = True, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters=None, true_values=None, false_values=None, skipinitialspace: 'bool' = False, skiprows=None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values=None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool' = False, skip_blank_lines: 'bool' = True, parse_dates=None, infer_datetime_format: 'bool' = False, keep_date_col: 'bool' = F

In [4]:
adv1_df = pd.read_csv('advertising_1.csv', index_col='Number')

In [5]:
adv1_df.head(10)

Daily Time Spent on Site  Daily Internet Usage  \
Number                                                   
5                          68.95                256.09   
6                          80.23                193.77   
8                          74.15                245.89   
9                            NaN                225.58   
10                         59.99                226.74   
11                         88.91                208.36   
12                           NaN                131.76   
13                         74.53                   NaN   
14                         69.88                183.82   
15                         47.64                122.02   

                                Ad Topic Line  Clicked on Ad  
Number                                                        
5          Cloned 5thgeneration orchestration              0  
6          Monitored national standardization              0  
8       Triple-buffered reciprocal time-frame              0  
9               Robust logistical utilization              0  
10            Sharable client-driven software              0  
11                 Enhanced dedicated support              0  
12                   Reactive local challenge              1  
13             Configurable coherent function              0  
14         Mandatory homogeneous architecture              0  
15             Centralized neutral neural-net              1

***Задача 2***

Выведите размер датафрейма `adv1_df`.

In [6]:
size = adv1_df.shape
print(size)

(500, 4)


In [7]:
print(adv1_df.shape)

(500, 4)


***Задача 3***

Выведите cреднее ежедневное время нахождения в интернете пользователя под номером 8.

In [8]:
print(adv1_df.loc[8, 'Daily Internet Usage'].mean())  

245.89


***Задача 4***

Загрузите таблицу из файла `advertising_2.csv` и сохраните её в датафрейм `adv2_df`. Укажите в качестве индекса стоблец `Number`. Выведите на экран строки для пользователей с номерами с 533-го по 536-й.

In [9]:
adv2_df = pd.read_csv('advertising_2.csv', index_col='Number')

In [10]:
adv2_df.head(10)

Daily Time Spent on Site  Daily Internet Usage  \
Number                                                   
530                          NaN                165.27   
531                        43.65                   NaN   
532                        59.61                198.45   
533                        46.61                   NaN   
534                          NaN                162.03   
535                        65.10                118.10   
536                        53.44                   NaN   
537                        79.53                244.91   
538                        91.43                209.91   
539                        73.57                212.38   

                                       Ad Topic Line  Clicked on Ad  
Number                                                               
530                 Re-engineered impactful software              0  
531              Business-focused background synergy              1  
532     Future-proofed coherent budgetary management              0  
533                    Ergonomic methodical encoding              1  
534                Compatible dedicated productivity              0  
535                   Up-sized real-time methodology              1  
536            Up-sized next generation architecture              1  
537                  Managed 6thgeneration hierarchy              0  
538                         Organic motivating model              0  
539                Pre-emptive transitional protocol              0

In [11]:
print(adv2_df.iloc[5:8, 0]) 

Number
535    65.10
536    53.44
537    79.53
Name: Daily Time Spent on Site, dtype: float64


***Задача 5***

Выведите сводную таблицу описательных статистик для датафрейма `adv2_df`, вызвав необходимый метод на всём датафрейме. 

Глядя на вывод, напишите, столбец с каким названием не содержит незаполненных значений.

*Подсказка:*  В сводной таблице не содержится информации о количестве строк всего датафрейма, поэтому для сначала распечатайте общее количество строк датафрейма.

*Рекомендация:* Кроме изученного метода `describe` для описания датафрейма и получения информации о пропущенных значениях полезен метод [`info`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html).

In [12]:
adv2_df.describe()

Daily Time Spent on Site  Daily Internet Usage  Clicked on Ad
count                184.000000            184.000000     200.000000
mean                  66.494728            186.809674       0.420000
std                   15.414725             43.844580       0.494797
min                   32.910000            108.030000       0.000000
25%                   52.805000            148.955000       0.000000
50%                   71.150000            194.170000       0.000000
75%                   78.352500            225.372500       1.000000
max                   91.430000            259.760000       1.000000

In [13]:
print(adv2_df.shape[0])
adv2_df.describe().T
def no_blank_cols(df):
    cols = [col for col in df.columns if df[col].isna().sum() < 0]
    print(cols)

200


In [14]:
adv2_df.shape

(200, 4)

In [15]:
adv2_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 200 entries, 530 to 739
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Daily Time Spent on Site  184 non-null    float64
 1   Daily Internet Usage      184 non-null    float64
 2   Ad Topic Line             200 non-null    object 
 3   Clicked on Ad             200 non-null    int64  
dtypes: float64(2), int64(1), object(1)
memory usage: 7.8+ KB


In [16]:
print('Total number of rows:', len(adv2_df))
summary = adv2_df.describe()


no_missing = summary.columns[summary.loc['count'] == len(adv2_df)]

print('Не содержит незаполненных значений столбец:', no_missing[0])
print(summary)

Total number of rows: 200
Не содержит незаполненных значений столбец: Clicked on Ad
       Daily Time Spent on Site  Daily Internet Usage  Clicked on Ad
count                184.000000            184.000000     200.000000
mean                  66.494728            186.809674       0.420000
std                   15.414725             43.844580       0.494797
min                   32.910000            108.030000       0.000000
25%                   52.805000            148.955000       0.000000
50%                   71.150000            194.170000       0.000000
75%                   78.352500            225.372500       1.000000
max                   91.430000            259.760000       1.000000


In [30]:
print('Total number of rows:', len(adv2_df))
no_missing = adv2_df.columns[adv2_df.notnull().all()]
print('Columns without missing values:', list(no_missing))

Total number of rows: 200
Columns without missing values: ['Ad Topic Line', 'Clicked on Ad']


In [18]:
missing_data = adv2_df[adv2_df['Clicked on Ad'].isnull()]
print(missing_data)

Empty DataFrame
Columns: [Daily Time Spent on Site, Daily Internet Usage, Ad Topic Line, Clicked on Ad]
Index: []


***Задача 6***

Добавьте к датафрейму `adv1_df` в конец датафрейм `adv2_df` с помощью метода `append`. 

Сохраните объединенный датафрейм в новой переменной `adv12_df` и распечатайте его.

In [19]:
adv12_df = adv1_df.append(adv2_df)
print(adv12_df)

        Daily Time Spent on Site  Daily Internet Usage  \
Number                                                   
5                          68.95                256.09   
6                          80.23                193.77   
8                          74.15                245.89   
9                            NaN                225.58   
10                         59.99                226.74   
...                          ...                   ...   
735                        65.53                190.17   
736                        61.87                   NaN   
737                        83.16                   NaN   
738                        44.11                121.24   
739                        56.57                131.98   

                                    Ad Topic Line  Clicked on Ad  
Number                                                            
5              Cloned 5thgeneration orchestration              0  
6              Monitored national standardiz

C:\Users\user\AppData\Local\Temp\ipykernel_11420\2213267692.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  adv12_df = adv1_df.append(adv2_df)


In [31]:
adv12_df = pd.concat([adv1_df, adv2_df])
print(adv12_df)

        Daily Time Spent on Site  Daily Internet Usage  \
Number                                                   
5                          68.95                256.09   
6                          80.23                193.77   
8                          74.15                245.89   
9                            NaN                225.58   
10                         59.99                226.74   
...                          ...                   ...   
735                        65.53                190.17   
736                        61.87                   NaN   
737                        83.16                   NaN   
738                        44.11                121.24   
739                        56.57                131.98   

                                    Ad Topic Line  Clicked on Ad  
Number                                                            
5              Cloned 5thgeneration orchestration              0  
6              Monitored national standardiz

***Задача 7***

Для объединённого датафрейма `adv12_df` распечатайте среднее время, проводимое пользователем на сайте компании.

In [21]:
print(adv12_df['Daily Time Spent on Site'].mean())

65.57268138801263


***Задача 8***

Из объединённого датафрейма `adv12_df` выберите и распечатайте строки только с теми пользователями, для которых неизвестно среднее ежедневное время, проводимое пользователем на сайте компании.

In [22]:
missing_data = adv12_df[adv12_df['Daily Time Spent on Site'].isnull()]
print(missing_data)

        Daily Time Spent on Site  Daily Internet Usage  \
Number                                                   
9                            NaN                225.58   
12                           NaN                131.76   
19                           NaN                143.56   
27                           NaN                164.83   
34                           NaN                209.82   
...                          ...                   ...   
672                          NaN                235.97   
674                          NaN                126.44   
685                          NaN                200.71   
690                          NaN                226.69   
731                          NaN                225.05   

                                  Ad Topic Line  Clicked on Ad  
Number                                                          
9                 Robust logistical utilization              0  
12                     Reactive local challenge   

***Задача 9***

Загрузите таблицу из файла `advertising_3.csv` и сохраните её в датафрейм `adv3_df`. Укажите в качестве индекса стоблец `Number`. Выведите на экран столбцы `Ad Topic Line` и `Clicked on Ad`.

In [32]:
adv3_df = pd.read_csv('advertising_3.csv', index_col='Number')

In [33]:
print(adv3_df[['Ad Topic Line', 'Clicked on Ad']])

                                       Ad Topic Line  Clicked on Ad
Number                                                             
740                 Distributed bifurcated challenge              0
741       Customizable zero-defect Internet solution              0
742     Self-enabling zero administration neural-net              1
744           Open-architected system-worthy ability              0
745               Quality-focused maximized extranet              1
...                                              ...            ...
999                    Front-line bifurcated ability              1
1000                   Fundamental modular algorithm              1
1001                 Grass-roots cohesive monitoring              1
1002                    Expanded intangible solution              1
1003            Proactive bandwidth-monitored policy              0

[251 rows x 2 columns]


***Задача 10***

Добавьте к датафрейму `adv12_df` в конец датафрейм `adv3_df` с помощью метода `concat`. Явно пропишите значение параметра `axis`.

Сохраните объединённый датафрейм в новой переменной `adv123_df` и распечатайте его.

In [34]:
adv123_df = pd.concat([adv12_df, adv3_df], axis=0)
print(adv123_df)

        Daily Time Spent on Site  Daily Internet Usage  \
Number                                                   
5                          68.95                256.09   
6                          80.23                193.77   
8                          74.15                245.89   
9                            NaN                225.58   
10                         59.99                226.74   
...                          ...                   ...   
999                        43.70                173.01   
1000                       72.97                208.58   
1001                       51.30                   NaN   
1002                       51.63                120.37   
1003                       55.55                187.95   

                                Ad Topic Line  Clicked on Ad  
Number                                                        
5          Cloned 5thgeneration orchestration              0  
6          Monitored national standardization           

***Задача 11***

Для объединённого датафрейма `adv123_df` выберите только те строки, в которых пользователи кликнули на рекламное сообщение. Сохраните полученный результат в датафрейм `success_adv_df`, распечатайте размер нового датафрейма.

In [35]:
success_adv_df = adv123_df[adv123_df['Clicked on Ad'] > 0]
print(success_adv_df['Clicked on Ad'].count())

475


***Задача 12***

Загрузите таблицу с данными пользователей из файла `users.csv` и сохраните её в датафрейм `users_df`. Индекс не указывайте.

Распечатайте сам датафрейм и сводную таблицу со статистиками для него.

In [36]:
import pandas as pd

users_df = pd.read_csv('users.csv')
print(users_df)
print(users_df.describe())

     Number   Age  Male            City                 Country  Area Income
0         5   NaN   0.0     Wrightburgh                 Tunisia     61833.90
1         6  31.0   NaN       West Jodi                   Nauru     68441.85
2         7  26.0   0.0        Davidton              San Marino     59785.94
3         8  29.0   1.0  West Terrifurt                   Italy     54806.18
4         9   NaN   0.0    South Manuel                 Iceland     73889.99
..      ...   ...   ...             ...                     ...          ...
975    1000  30.0   NaN       Duffystad                 Lebanon     71384.57
976    1001  45.0   1.0     New Darlene  Bosnia and Herzegovina     67782.17
977    1002  51.0   NaN   South Jessica                Mongolia     42415.72
978    1003  19.0   0.0     West Steven               Guatemala     41920.79
979    1004  26.0   0.0     Ronniemouth                  Brazil     29875.80

[980 rows x 6 columns]
            Number         Age        Male   Area In

***Задача 13***

Глядя на статистики `users_df`, укажите значения, удовлетворяющие следующим условиям:
1. Возраст самого молодого пользователя сайта: *ваш_ответ*
2. Максимальный средний доход в месте жительства пользователя сайта: *ваш_ответ*
3. Средний возраст пользователя сайта: *ваш_ответ*
4. Количество заполненных значений для колонки, содержащей информацию о том, является пользователь мужчиной или нет: *ваш_ответ*
5. Минимальный номер пользователя: *ваш_ответ*

В этом задании не требуется выбирать по условиям и распечатывать значения, достаточно внимательно посмотреть на статистики и скопировать нужные значения согласно вопросам.

In [37]:
success_adv_df = success_adv_df.reset_index()
success_full_df = pd.merge(success_adv_df, users_df, on='Number')
print(success_full_df)

     Number  Daily Time Spent on Site  Daily Internet Usage  \
0        12                       NaN                131.76   
1        15                     47.64                122.02   
2        17                     69.57                113.12   
3        19                       NaN                143.56   
4        20                     63.45                140.64   
..      ...                       ...                   ...   
459     997                     69.17                123.62   
460     999                     43.70                173.01   
461    1000                     72.97                208.58   
462    1001                     51.30                   NaN   
463    1002                     51.63                120.37   

                             Ad Topic Line  Clicked on Ad   Age  Male  \
0                 Reactive local challenge              1  48.0   1.0   
1           Centralized neutral neural-net              1  49.0   NaN   
2    Centralized content

***Задача 14***

К полученному датафрейму с успешными рекламными сообщениями `success_adv_df` добавьте справа информацию из датафрейма с пользователями `users_df` и сохраните в датафрейм `success_full_df`. В полученном датафрейме должны остаться только те пользователи, номера которых есть в обоих датафреймах. Для этого воспользуйтесь методом `merge` и пропишите явно верные параметры.

Затем распечатайте датафрейм.

*Важно:*

Объединять датафреймы с помощью `merge` можно и по индексам, и по столбцам с разными названиями. 
Так как общие значения содержатся в столбце `Number`, но в датафрейме `users_df` данный столбец является обычным столбцом, а в `success_adv_df` является индексом, перед тем как объединять, переведите столбец `Number` в `success_adv_df` в обычный столбец.

Для этого перед объединением пропишите:
```
success_adv_df = success_adv_df.reset_index()
```

[Подробнее о reset_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html)

In [38]:
success_adv_df = success_adv_df.reset_index()
success_full_df = pd.merge(success_adv_df, users_df, on='Number')
print(success_full_df)

     index  Number  Daily Time Spent on Site  Daily Internet Usage  \
0        0      12                       NaN                131.76   
1        1      15                     47.64                122.02   
2        2      17                     69.57                113.12   
3        3      19                       NaN                143.56   
4        4      20                     63.45                140.64   
..     ...     ...                       ...                   ...   
459    470     997                     69.17                123.62   
460    471     999                     43.70                173.01   
461    472    1000                     72.97                208.58   
462    473    1001                     51.30                   NaN   
463    474    1002                     51.63                120.37   

                             Ad Topic Line  Clicked on Ad   Age  Male  \
0                 Reactive local challenge              1  48.0   1.0   
1           C

***Задача 15***

Для объединённого датафрейма с пользователями, которые кликнули на рекламное сообщение `success_full_df`, отобразите сводную таблицу со статистиками для строковых колонок (`Ad Topic Line`, `City`, `Country`).


In [39]:
pd.pivot_table(success_full_df,  
                index=['Ad Topic Line', 'City', 'Country'],
                values=['Clicked on Ad'],  
                aggfunc='count',  
                margins=True,  
                margins_name='Total')

Clicked on Ad
Ad Topic Line                           City            Country                           
Adaptive context-sensitive application  Joneston        China                            1
Adaptive contextually-based methodology Port Paultown   Austria                          1
Adaptive demand-driven knowledgebase    Colebury        Tuvalu                           1
Adaptive uniform capability             East Georgeside Bahamas                          1
Advanced 24/7 productivity              Millertown      Russian Federation               1
...                                                                                    ...
Vision-oriented optimizing middleware   Jessicahaven    Cambodia                         1
Vision-oriented system-worthy forecast  Johnsontown     Brunei Darussalam                1
Visionary asymmetric encryption         South Lauratown Japan                            1
Visionary maximized process improvement Hamiltonfort    Trinidad and Tobago              1
Total                                                                                  380

[381 rows x 1 columns]

***Задача 16***

Для объединённого датафрейма с пользователями, которые кликнули на рекламное сообщение `success_full_df`, выведите страну и количество вхождений этой страны в датафрейм.


In [40]:
success_full_df['Country'].value_counts().reset_index().rename(columns={'index':'country', 'Country':'count'})

country  count
0          Ethiopia      7
1         Australia      6
2            Turkey      6
3           Liberia      6
4           Senegal      5
..              ...    ...
198         Ukraine      1
199  United Kingdom      1
200      Montserrat      1
201     Timor-Leste      1
202         Comoros      1

[203 rows x 2 columns]

***Задача 17***

Для объединённого датафрейма с пользователями, которые кликнули на рекламное сообщение `success_full_df`, выведите строки с данными пользователей из страны, название которой встречается чаще остальных.


In [41]:
most_common_country = success_full_df['Country'].value_counts().index[0]
results = success_full_df[success_full_df['Country'] == most_common_country]
print(results)

     index  Number  Daily Time Spent on Site  Daily Internet Usage  \
245    249     525                     46.61                136.18   
246    250     526                     63.26                120.46   
278    283     606                     52.13                118.27   
297    303     650                       NaN                137.97   
299    305     652                     46.43                137.20   
417    426     919                     41.86                128.62   
423    433     930                       NaN                   NaN   

                                       Ad Topic Line  Clicked on Ad   Age  \
245              Progressive intermediate throughput              1  42.0   
246                    Customizable holistic archive              1  29.0   
278                 Open-source even-keeled database              1  50.0   
297      Seamless bandwidth-monitored knowledge user              1  28.0   
299  Reverse-engineered background Graphic Interface  

***Задача 18***

Для объединённого датафрейма с пользователями, которые кликнули на рекламное сообщение `success_full_df`, выведите строки с данными пользователей из страны, название которой встречается чаще остальных, они проводят в интернете в среднем больше 120 минут и их возраст меньше 30 лет. 
Cохраните получившиеся строки в новый датафрейм `filtered_df`.


In [44]:
most_common_country = success_full_df['Country'].value_counts().index[0]
filtered_df = success_full_df[(success_full_df['Country'] == most_common_country) &
                              (success_full_df['Daily Internet Usage'] > 120) &   
                              (success_full_df['Age'] < 30)]  

filtered_df = filtered_df
print(filtered_df)

     index  Number  Daily Time Spent on Site  Daily Internet Usage  \
246    250     526                     63.26                120.46   
297    303     650                       NaN                137.97   
299    305     652                     46.43                137.20   

                                       Ad Topic Line  Clicked on Ad   Age  \
246                    Customizable holistic archive              1  29.0   
297      Seamless bandwidth-monitored knowledge user              1  28.0   
299  Reverse-engineered background Graphic Interface              1  28.0   

     Male        City   Country  Area Income  
246   1.0  East Donna  Ethiopia     54787.37  
297   1.0   Markhaven  Ethiopia     39723.97  
299   1.0   Brianland  Ethiopia     53922.43  


***Задача 19***

Для получившегося датафрейма `filtered_df` выведите строки с данными пользователей, для которых либо не указано среднее время, проведённое на сайте, либо указанное время больше 55 минут. Cохраните получившиеся строки в новый датафрейм `filtered_df2`.


In [46]:
filtered_df2 = filtered_df[(filtered_df['Daily Internet Usage'].isna()) |  
                           (filtered_df['Daily Internet Usage'] > 55)]
   
filtered_df2 = filtered_df2
print(filtered_df2)  

     index  Number  Daily Time Spent on Site  Daily Internet Usage  \
246    250     526                     63.26                120.46   
297    303     650                       NaN                137.97   
299    305     652                     46.43                137.20   

                                       Ad Topic Line  Clicked on Ad   Age  \
246                    Customizable holistic archive              1  29.0   
297      Seamless bandwidth-monitored knowledge user              1  28.0   
299  Reverse-engineered background Graphic Interface              1  28.0   

     Male        City   Country  Area Income  
246   1.0  East Donna  Ethiopia     54787.37  
297   1.0   Markhaven  Ethiopia     39723.97  
299   1.0   Brianland  Ethiopia     53922.43  


**Дополнительные задачи**

***Задача 20***

Для датафрейма `adv123_df` выведите строки с данными, заголовок рекламного сообщения в которых включает слово `model`.

Для этого вам понадобится метод [`contains`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.contains.html).

Cохраните получившиеся строки в новый датафрейм `model_df`.


In [48]:
model_df = adv123_df[adv123_df['Ad Topic Line'].str.contains('model')]
model_df = model_df
print(model_df)    

        Daily Time Spent on Site  Daily Internet Usage  \
Number                                                   
62                         44.98                129.31   
119                        69.00                   NaN   
202                        78.57                   NaN   
211                        76.90                212.67   
314                          NaN                161.16   
350                        65.77                   NaN   
501                        81.10                216.49   
538                        91.43                209.91   
629                        78.17                192.27   
712                        81.90                225.47   
823                        81.98                212.88   
995                        35.79                165.62   

                              Ad Topic Line  Clicked on Ad  
Number                                                      
62                   Organized global model              1  
119 

***Задача 21***

Для получившегося датафрейма `model_df` выведите строки с данными пользователей, которые проводят на сайте больше среднего времени по всем пользователям в данном датафрейме. Cохраните получившиеся строки в новый датафрейм `model_popular_df`.


In [49]:
mean_usage = model_df['Daily Internet Usage'].mean()
model_popular_df = model_df[model_df['Daily Internet Usage'] > mean_usage]
model_popular_df = model_popular_df
print(model_popular_df)

        Daily Time Spent on Site  Daily Internet Usage  \
Number                                                   
211                        76.90                212.67   
501                        81.10                216.49   
538                        91.43                209.91   
629                        78.17                192.27   
712                        81.90                225.47   
823                        81.98                212.88   

                              Ad Topic Line  Clicked on Ad  
Number                                                      
211           Synchronized multimedia model              0  
501                Front-line dynamic model              0  
538                Organic motivating model              0  
629                  Automated mobile model              0  
712     Multi-channeled 3rdgeneration model              0  
823                Up-sized maximized model              0  


***Задача 22***

Для объединённого датафрейма `model_popular_df` выведите строки с данными пользователей, номера которых равны 501, 712 и 823. 

Для этого вам понадобится метод [`isin`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isin.html).

*Подсказка:* Не забудьте, что номера пользователей находятся не в обычной колонке, а в колонке, являющейся индексом, поэтому вам необходимо получить значения индекса, а не обычной колонки.

In [51]:
user_ids = [501, 712, 823]
results = model_popular_df.loc[model_popular_df.index.isin(user_ids)]
print(results)

        Daily Time Spent on Site  Daily Internet Usage  \
Number                                                   
501                        81.10                216.49   
712                        81.90                225.47   
823                        81.98                212.88   

                              Ad Topic Line  Clicked on Ad  
Number                                                      
501                Front-line dynamic model              0  
712     Multi-channeled 3rdgeneration model              0  
823                Up-sized maximized model              0  
